### PR TITLE
Fix typos in readme

### PR DESCRIPTION
**Pull request by odow**
Diff came up weird:
- `Normally the` -> `Normally this`
- `tme` -> `time`
- `behavir` -> `behavior` (Or maybe we should use NZ spelling since it's called Pukeko?)

### CODE REVIEW

**Comment by IainNZ** [comment]
Go with the NZ spelling!
Diff is weird - did anything actually change in photo credit line?

**Comment by odow** [comment]
No. I just used the online editor. Maybe it added a newline?

**Comment by IainNZ** [comment]
My functions right now: https://www.youtube.com/watch?v=vt1Pwfnh5pc

**Comment by IainNZ** [comment]
Thanks!

**Pull request merged**
